name: Node CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:



    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: npm ci
      run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}



    - name: npm test
      run: PATH=node_modules/.bin:$PATH $(jq -r '.scripts.test' < package.json)
      env:
        
        CI: true
